<!-- BEGIN Footer -->

<div id="footer">
<!-- begin:  LINKS -->
<table class="footer_sections" cellspacing="0">
<tr>
	<td class="footer_sections_left">Partner Volunteer Sites: </td>
	<td class="footer_sections_right">
		<a href="http://ccda.christianvolunteering.org">CCDA</a><br/>
		<a href="http://uywi.christianvolunteering.org">UYWI</a><br/>
		<a href="http://hlic.christianvolunteering.org">HLIC</a><br/>
	</td>
	<td class="footer_sections_right">
		<a href="http://agrm.christianvolunteering.org">AGRM</a><br/>
		<a href="http://putyourfaithinaction.christianvolunteering.org">FaithInAction</a><br/>
		<a href="http://youthpartnersnet.christianvolunteering.org">YouthPartnersNet</a><br/>
	</td>
	<td class="footer_sections_right">
		<!--<a href="http://salvationarmy.christianvolunteering.org">Salvation Army</a><br/> -->
		<a href="http://volunteer.gospel.com">Gospel.com</a><br/>
		<a href="http://www.ivolunteering.org">iVolunteering</a>
	</td>
</tr>

<% if(  (aszHostID.equalsIgnoreCase("voleng1")) ||
		(aszHostID.equalsIgnoreCase("volengdefault")) 
){ %>  
<tr>
	<td class="footer_sections_left"> Regional Volunteer Sites:</td>
	<td class="footer_sections_right">
		<a href="http://chicago.christianvolunteering.org">Chicago</a><br/>
		<a href="http://denver.christianvolunteering.org">Denver</a><br/> 
		<a href="http://indy.christianvolunteering.org">Indianapolis</a><br/> 
	</td>
	<td class="footer_sections_right">
		<a href="http://losangeles.christianvolunteering.org">Los Angeles</a><br/>
		<a href="http://miami.christianvolunteering.org">Miami</a><br/> 
		<a href="http://newengland.christianvolunteering.org">New England</a><br/>  
		<a href="http://newyork.christianvolunteering.org">New York</a><br/> 
	</td>
	<td class="footer_sections_right">
		<a href="http://seattle.christianvolunteering.org">Seattle</a><br/>
		<a href="http://twincities.christianvolunteering.org">Twin Cities</a><br/>
		<a href="http://www.christianvolunteering.org/city.jsp">City Sitemap</a><br/>
		<a href="zipmap.jsp">Zip Code Sitemap</a>
	</td>
</tr>
<% } %>

<tr>
	<td class="footer_sections_left">Sections:</td>
	<td class="footer_sections_right">
	<a href="http://www.christianvolunteering.org/churchvolunteer.jsp" title="Church Volunteers' Resources and Search">Church Volunteer Resources</a><br/> 
		<a href="http://www.christianvolunteering.org/shorttermmissions.jsp" title="Short Term Missions Trip Search">Short Term Missions</a><br/>
	</td>
	<td class="footer_sections_right">
		<a href="http://www.christianvolunteering.org/organizationlistings.jsp">Org Sitemap</a><br/>
		<a href="http://www.urbanministry.org/wiki/encyclopedia-volunteer-management-volunteering-and-short-term-missions">Volunteer Management Wiki</a><br/>
		<a href="http://www.urbanministry.org/faceted_search/results/taxonomy:4700,4599" title="Sermon Outlines on Justice and Service for Church Leaders">Sermon Outlines</a><br/> 
	</td>
	<td class="footer_sections_right">
		<a href="http://www.christianvolunteering.org/virtualvolunteer.jsp"> 
		Virtual Volunteering</a><br/>
		<a href="/volunteerlistings.jsp" title="Christian volunteer, church volunteer, urban ministry service, and short term missions volunteer listings">Volunteer Listings</a><br/>
		<a href="http://www.urbanministry.org/faceted_search/results/taxonomy:113,4599" title="Bible Studies on Justice and Service for Church Leaders, Small Groups, and Church Volunteers">Bible Studies</a><br/> 
	</td>
</tr>

<tr>
	<td class="footer_sections_left">TechMission Sites:</td>
	<td class="footer_sections_right">
<a href="http://www.techmission.org" title="Technology and Urban Ministry, Christian Community Computer Centers Addressing the Digital Divide">TechMission.org</a><br/>
<a href="http://www.urbanministry.org" title="UrbanMinistry.org: Urban ministry MP3s, talks, podcast, sermons, workshops, presentations, Webcasts, training, on racism, racial reconciliation, ethnic identity, classism, sexism, grants and church resources">UrbanMinistry.org</a><br/>
	</td>
	<td class="footer_sections_right">
	<a href="http://www.cityvision.edu" title="Online Urban Ministry Courses in Theology, Missions, Accounting, CFRE Fundraising, Management, Evangelism and Counseling">CityVision.edu</a><br/>
<a href="http://www.safefamilies.org" title="Free Parental Controls & Internet Filtering Software We-Blocker Download - Online Safety Workshops - Christian Accountability, Pornography and Sex Addiction Recovery">
SafeFamilies.org</a><br/>
	</td>
	<td class="footer_sections_right">
		<a href="http://www.christianfreeware.org/" title="Free Christian Software CD for download including church management software, worship projection, accountability software, freeware, open source ministry and Bible software"> 
		ChristianFreeware.org</a><br/>
		<a href="http://www.christianvolunteering.org" title="Christian Volunteer Directory: Volunteering for Urban Ministries and Short Term Urban Missions Opportunities">ChristianVolunteering.org</a> <br/>
	</td>
</tr>

</table><!-- end:LINKS -->

<table class="footer_links"><!-- Table that contains share buttn and CV links-->
<tr>
 <td style="text-align: left; padding-left:5px; padding-top: 30px;"><a href="http://www.gospel.com/"><img src="/imgs/GospelComAlliance_logo.png" alt="Gospel Communications Alliance Member" ></a></td> 

<!-- ADS INSERTED HERE -->
<td>
<div class="advertisement" id="group-tids-4496">
<script type="text/javascript" src="/modules_um/ad/serve.php?q=1&amp;k=7a15268e1dcf7769adc47075b2f267d1&amp;t=4496"></script>
</div>
</td>

<!--/ADS INSERTED-->

<td class="copyright">
<p>
Site Support Contact: <a href="mailto:info@christianvolunteering.org">info@christianvolunteering.org</a><br/>(617) 282-9798 x109
</p>

<p>
<!-- main page feed -->
<a href="http://www.urbanministry.org/frontpageview/feed"><img src="/files/images/rss-sm.png" alt="" title="" width="16" height="16" /> RSS</a> |
<!--/ main page feed -->
<!-- Buttn Facebook -->
<script>function fbs_click() {u=location.href;t=document.title;window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');return false;}</script>
<a href="http://www.facebook.com/share.php?u=<url>" class="fb_share_button" onclick="return fbs_click()" target="_blank" style="text-decoration:none;">Share</a> |
<!--/ Buttn Facebook -->
<a href="http://www.urbanministry.org/terms">privacy</a> | 
<a href="<%=request.getContextPath()%>/contact.jsp" title="Contact Christian Volunteering">contact</a> | 
<a href="mailto:feedback@christianvolunteering.org">feedback</a> | 
<a href="<%=request.getContextPath()%>/sitemap.jsp">sitemap</a> | 
<a href="https://www.urbanministry.org/civicrm/contribute/transact?reset=1&id=13">donate</a> <br/> 
  
</p>
</td>

</tr>
</table><!-- end: Table that contains UM logo, share buttn and UM links-->
