<!-- BEGIN Footer -->

<div id="footer"> <!-- align="center"-->

<% if(false){ //aszHostID.equalsIgnoreCase("voleng1")){ %>
	<iframe id="content" name="content" src="http://www.christianvolunteering.org/urbanministry/chrisvol_hooks/cv_subscriptions_footer_home.php" frameborder="0" width="820" height="50" scrolling="no" ></iframe>
<% } %>
	
<!--br-->

<%@ include file="/template_include/cv_footer.inc" %>


</div>

<%@ include file="/template_include/footer_google_analytics.inc" %>
<%@ include file="/template_include/footer_piwik.inc" %>

</body>
</html>
</div>
<!-- END Footer -->
