<a name="footer"></a>
<div id="footer-wrap">
<div id="footer-top">
<div id="footer-left">
<a href="http://webdev.getzapped.com/"><img src="imgs/abs_logo_footer2.gif" alt="American Bible Society" width="37" height="22"></a><ul><li>© 2009 American Bible Society&nbsp;|&nbsp;</li><li><a href="#legal">Legal</a>&nbsp;|&nbsp;</li>
<li><a href="http://www.bibles.com/pages/privacy" target="_blank">Privacy</a>&nbsp;|&nbsp;</li>
<li><a href="http://www.bibles.com/pages/financial" target="_blank">Financial</a>&nbsp;|&nbsp;</li>
<li><a href="#terms">Terms of Use</a>&nbsp;|&nbsp;</li>
<li><a href="http://www.bibles.com/pages/about-contactus" target="_blank">Contact</a></li>
</ul>

 </div>
 <div id="footer-right">
 <a href="http://www.independentcharities.org/info.asp?Title=The+ICA+Seal+of+Excellence&amp;sBody=BIA" target="_blank">
 <img src="imgs/footer_ica_logo2.png" alt="Independent Charities of America: Best in America Seal of Excellence" title="Independent Charities of America: Best in America Seal of Excellence" width="52" height="85">
 </a>
 
 </div>
 </div>
 </div>
 </div><!-- end ds-push  -->


<br>Joint with TechMission, Inc:<br>

<%@ include file="/template_include/cv_footer.inc" %>




</div> <!-- end #footer-->
  

</div><!-- /#page -->
</div><!-- /#wrap2 -->
</div><!-- /#wrap1 -->
</div><!-- /#wrap -->














<% if(  (aszPath.equalsIgnoreCase("/voleng2/myaccountsum1.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-start33.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-start44.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-summary66.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-addlisting.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-dupliclisting.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/volcreateacct1.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/drupal_setup.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-viewlisting1.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/iwanttohelp.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/emailconfirmation.jsp")) ||
                (false==true)
){ // don't load the google analytics here - it has already been loaded earlier in the page for goal tracking %>
<% } else { %>
<%@ include file="/template_include/footer_google_analytics.inc" %>

<% } %>
</body>
</html>

<!-- end file footer.inc -->


