<!-- BEGIN HEADER -->
<!--% 
ApplicationCodesBRLO aCodes2 = new ApplicationCodesBRLO( request );
ArrayList aService2List = new  ArrayList ( 2 );
aCodes2.getAppCodeList( aService2List, 161 );
%-->

<link rel="shortcut icon" href="http://www.americanbible.org/templates/abs/img/favicon/favicon.ico" type="image/x-icon">

<meta http-equiv="Content-Language" content="en-us">
<title>Ministry Resources :: American Bible Society </title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">

<META NAME="ROBOTS" CONTENT="INDEX, NOFOLLOW">
	
<link href="http://www.christianvolunteering.org/abs/template/csstyles.css" rel="stylesheet" type="text/css"> <!-- this is in the /hlic/ directory -->


<link href="http://www.christianvolunteering.org/abs/template/modular_abs.css" rel="stylesheet" type="text/css" />
<link href="http://www.christianvolunteering.org/template_include/jazzy.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/misc/jquery.js"></script>
<script type="text/javascript" src="/template_include/jquery.curvycorners.js"></script>




<script type="text/JavaScript">
<!--

function runSearch2(){
	zip = document.searchForm2.postalcode.value;
	cat = document.searchForm2.category1.value;
	if(cat == "" && zip == ""){
		return;
	}
	document.searchForm2.submit();
}

//-->
</script>

<SCRIPT TYPE="text/javascript">
<!--
function popup(mylink, windowname)
{
if (! window.focus)return true;
var href;
if (typeof(mylink) == 'string')
   href=mylink;
else
   href=mylink.href;
window.open(href, windowname, 'width=400,height=200,scrollbars=yes');
return false;
}
//-->
</SCRIPT>




</head>

<body topmargin="0">

<div id="wrapper">

<div id="contentwrapper">




	
<div id="wrap">
<div id="wrap1">
<div id="wrap2">
<div id="page">

<div id="head">
<div style="float: right; margin-top: -5px; margin-right: -14px; z-index: 9000; position: relative;">



<div id="header">

<div id="search-wrap">
<form action="/Search" method="get" name="SearchBoxForm"><input maxlength="55" value=" Search" size="18" onfocus="clear_searchbox();" alt="Search" name="Search" id="Search" type="text"><input value="GO" id="search-go" src="imgs/search_go.gif" alt="GO" type="image"><div id="search-options">Site <img src="imgs/radio_button_on.gif" alt="" width="14" height="14"> &nbsp; <img src="imgs/search_pipe.gif" alt="" width="2" height="18"> &nbsp; <span id="biblesearch">Bible Search <img src="imgs/radio_button_off.gif" alt="" width="14" height="14"></span></div></form>
<div id="BibleSearchWindowOuter">
<div id="BibleSearchWindow">
<div id="bible-search-wrap">
<div id="bible-search-head"><a href="#" id="BibleSearchClose"><img src="imgs/search_header_closex.gif" alt="close" width="364" height="36"></a></div>
<div id="bible-search"><img src="imgs/bible-search_head.gif" alt="Bible Search" width="364" height="50"><br>


	<h1><a href="http://www.americanbible.org/"><img src="imgs/abs_logo.png" alt="American Bible Society" width="247" height="32"></a></h1>


	<a name="navigation"></a>
<div id="head-bot"><div id="main-nav-wrap"><div id="main-nav"><ul class="sf-menu sf-js-enabled sf-shadow">

					<li class="nav-home nav-on">
						<a class="sf-with-ul" href="#">Home</a>
					</li>
					<li class="nav-spacer">&nbsp;</li>
					<li class="nav-engage">
						<a class="sf-with-ul" href="#">Engage God's Word</a>
						<ul id="subnav-engage" style="display: none; visibility: hidden;">
							<li class=""><a href="#">Bible Thinger</a></li>

							<li class=""><a href="#">Bible Resources</a></li>
							<li class=""><a href="#">Bible Engagement</a></li>
							<li class=""><a href="#">Ministry Resources</a></li>
							<li class=""><a href="#">Share Your Story Now</a></li>
						</ul>
					</li>
					<li class="nav-spacer">&nbsp;</li>

					<li class="nav-get">
						<a class="sf-with-ul" href="#">Get God's Word</a>
						<ul id="subnav-get" style="display: none; visibility: hidden;">
							<li><a href="#">Bible Store</a></li>
							<li><a href="#">Bible News</a></li>
							<li><a href="#">Daily Bible</a></li>
							<li><a href="#">Bible Subscriptions</a></li>

							<li><a href="#">MoBia</a></li>
							<li><a href="#">Nida Institute</a></li>	
						</ul>
					</li>
					<li class="nav-spacer">&nbsp;</li>
					<li class="nav-give">
						<a class="sf-with-ul" href="#">Give God's Word</a>
						<ul id="subnav-give" style="display: none; visibility: hidden;">

							<li class=""><a href="#">Bible Passport</a></li>
							<li class=""><a href="#">Support Bible Ministry</a></li>
							<li class=""><a href="#">Planned Giving</a></li>
							<li class=""><a href="#">Donor Services</a></li>
						</ul>
					</li>
					<li class="nav-spacer">&nbsp;</li>

					<li class="nav-about">
						<a class="sf-with-ul" href="#">About ABS</a>
						<ul id="subnav-about" style="display: none; visibility: hidden;">
							<li><a href="#">Mission</a></li><li><a href="#">Finances</a></li><li><a href="#">Press/News</a></li><li><a href="#">Careers</a></li><li><a href="#">Volunteer</a></li><li><a href="#">Contact</a></li>
						</ul>

					</li>
				</ul></div></div></div>
</div><!-- end: div head-->
	
	
	


<!-- END HEADER -->

