<br/><br/><br/>
<div id="footer">
<!-- begin: TechMission Program Site LINKS -->
<table class="footer_sections" cellpadding="0" cellspacing="0">
  <tr>
    <td class="footer_sections_left"> Partners' Sections:</td>
    
	<td class="footer_sections_right">
	<a href="http://www.urbanministry.org/ccda" title="Christian Community Development Association" target="_blank">CCDA</a> <br />
	<a href="http://www.urbanministry.org/fasten"  title="Faith and Service Technical Education Network" target="_blank">FASTEN</a><br />
	<a href="http://www.urbanministry.org/agrm" title="Association of Gospel Rescue Missions" target="_blank">AGRM</a><br/>
	<a href="http://www.urbanministry.org/youthpartnersnet-compassionworks" title="CompassionWorks/YouthPartnersNet" target="_blank">YouthPartnersNet</a>
      </td>
    
	<td class="footer_sections_right">


	 <a href="http://www.urbanministry.org/kingdomworks" title="Kingdomworks" target="_blank">Kingdomworks</a><br />
	 <a href="http://www.urbanministry.org/emmanuel-gospel-center-0" title="EGC" target="_blank">Emmanuel Gospel Center</a><br />
	 <a href="http://www.urbanministry.org/heres-life-inner-city" title="HLIC" target="_blank">Here's Life Inner City</a><br />
	 <a href="http://www.urbanministry.org/esa" title="Evangelicals for Social Action (ESA)">Evangelicals for Social Action</a><br/>
	 <a href="http://www.urbanresource.net">UrbanResource.net</a>
	 </td>
	 
	 <td class="footer_sections_right">
	 <a href="http://www.urbanministry.org/faithinaction" title="Putting Your Faith in Action" target="_blank">FaithInAction</a><br />
	 <a href="http://www.urbanministry.org/world-vision" title="World Vision" target="_blank">World Vision</a><br />
     <a href="http://www.urbanministry.org/urbnet-1"  title="UrbNet" target="_blank">UrbNet</a><br />
<a href="http://www.urbanministry.org/urban-onramps"  title="Urban Onramps" target="_blank">Urban Onramps</a>
	 </td>
  </tr>
  
  <tr>
    <td class="footer_sections_left"> UrbanMinistry.org Links:</td>
    
	<td class="footer_sections_right">
	<strong>TechMission Websites:</strong><br />
	<a href="http://www.cityvision.edu" title="Online Urban Ministry Courses in Theology, Missions, Accounting, CFRE Fundraising, Management, Evangelism and Counseling">CityVision.edu: Urban Ministry Courses</a><br/>
	<a href="http://www.christianvolunteering.org" target="_blank" title="Christian Volunteer Directory: Volunteering for Urban Ministries and Short Term Urban Missions Opportunities">ChristianVolunteering.org</a><br/>
        <a href="http://www.safefamilies.org" target="_blank" title="Free Parental Controls & Internet Filtering Software We-Blocker Download - Online Safety Workshops - Christian Accountability, Pornography and Sex Addiction Recovery">SafeFamilies.org</a><br/>
		<a href="http://www.blazinggrace.org" target="_blank" title="Recovery from Pornography Addiction, Christian Accountability Forums">BlazingGrace.org</a><br/>
		<a href="http://www.urbanministry.org" target="_blank" title="UrbanMinistry.org: Urban ministry MP3s, talks, podcast, sermons, workshops, presentations, Webcasts, training, on racism, racial reconciliation, ethnic identity, classism, sexism, grants and church resources">UrbanMinistry.org</a><br />
        <a href="http://www.christianfreeware.org" target="_blank" title="Christian Freeware: Free Christian Software CD for download including church management software, worship projection, accountability software, freeware, open source ministry and Bible software">ChristianFreeware.org</a><br />
		<a href="http://www.techmission.org" target="_blank" title="Technology and Urban Ministry, Christian Community Computer Centers Addressing the Digital Divide">TechMission.org</a><br/>
    </td>
	
	<td class="footer_sections_right">
	<strong>Encyclopedia Sections:</strong><br />
	<a href="http://www.urbanministry.org/wiki/encyclopedia-urban-ministry" title="Community development & urban ministry program resources, faith-based organization research, nonprofit management, capacity building, church development resources">Urban Ministry</a><br />
	<a href="http://www.urbanministry.org/wiki/encyclopedia-christian-community-technology" title="Christian community technology center resources, digital divide, international development, online segregation, social inclusion">Christian Community Technology</a><br />
	<a href="http://www.urbanministry.org/wiki/encyclopedia-urban-youth-ministry-wiki" title="Youth technology curriculum, lesson plans, after-school program development, youth entrepreneurship/teen programs, TechMission Corps replicable project resources">Urban Youth Ministry</a><br />
		<a href="http://www.christiangrantsdirectory.org" title="Christian grants, nonprofit grants, secular social-service funders">Christian Grants  Directory</a> and <a href="http://www.urbanministry.org/wiki/encyclopedia-grant-writing-and-fund-raising">Training</a><br />
	<a href="http://www.urbanministry.org/wiki/encyclopedia-recovery-and-addiction-wiki" title="Pornography addiction recovery, substance abuse recovery, 12-step programs, accountability groups, Internet filtering software reviews">Recovery and Addiction</a><br/>
	<a href="http://www.urbanministry.org/todaysblogs" title="Blogs from Top Urban Ministry Leaders">Today's Top Urban Ministry Bloggers</a>
	</td>
	<td class="footer_sections_right">
	<strong>Volunteer/Staffing Resources:</strong><br />
	<a href="http://www.urbanministry.org/wiki/encyclopedia-volunteer-management-volunteering-and-short-term-missions" title="Volunteering; volunteer management - recruitment, training, recognition; short-term missions; personality, vocation, calling, spiritual gifts resources">Volunteer Wiki Encyclopedia</a><br />
	<a href="http://www.urbanchristianjobs.org" title="Urban Ministry job search database">Post/Search Urban Ministry Jobs</a><br/>
	<a href="http://www.urbanministry.org/paid-urban-ministry-internships" title="40 Paid Urban Ministry Internships - AmeriCorps Service Positions in Boston, Chicago, Denver, Los Angeles">40 Paid Urban Ministry Internships</a><br/>
	<a href="http://www.urbanministry.org/wiki/webcast-workshops-volunteers" title="Volunteer Training Workshop Presentations">Webcast Presentations</a><br />
	<a href="http://www.christianvolunteering.org/churchvolunteer.jsp" title="Church Volunteers' Resources and Search">Church Volunteer Resources</a><br />
	<a href="http://www.christianvolunteering.org/shorttermmissions.jsp" title="Short-Term Missions, Christian Urban Internships, missions search for group missions trips, youth trips">Short Term Missions Search</a><br />
	<a href="http://www.urbanministry.org/spiritual_gifts" title="Spiritual gifts tests and Christian self-discovery resources">Spiritual Gifts </a> and <a href="http://www.urbanministry.org/wiki/personality-vocation-and-calling" title="Personality tests, Christian calling and vocation">Personality Tests</a></td>
	
  </tr>
</table>


<table class="footer_links"><!-- Table that contains UM logo, share buttn and UM links-->
<tr>
<td style="text-align: left; padding-left:5px; vertical-align: middle;"></td>

<!-- ADS INSERTED HERE -->
<td class="techsupport">
<!--start-->
<div class="advertisement" id="group-tids-4496"><script type="text/javascript" src="http://www.urbanministry.org/sites/all/modules/ad/serve.php?q=1&amp;k=7a15268e1dcf7769adc47075b2f267d1&amp;t=4496"></script></div>
<!--end-->
 </td>
<!--/ADS INSERTED-->

<td class="copyright" valign="top" >Except where otherwise noted, this work is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/2.0/"><u>Creative Commons</u></a> 
<br/>
<%@ include file="/template_include/cv_footer.inc" %>
</td>

</tr>
</table><!-- end: Table that contains UM logo, share buttn and UM links-->

</td>
</tr>
</table>


<!-- end file um_footer.inc -->


        </div>
  </div>
  </div>




</div>

<% if(  (aszPath.equalsIgnoreCase("/voleng2/myaccountsum1.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-start33.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-start44.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-summary66.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-addlisting.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-dupliclisting.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/volcreateacct1.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/drupal_setup.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/nonp-viewlisting1.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/iwanttohelp.jsp")) ||
                (aszPath.equalsIgnoreCase("/voleng2/emailconfirmation.jsp")) ||
                (false==true)
){ // don't load the google analytics here - it has already been loaded earlier in the page for goal tracking %>
<% } else { %>
<%@ include file="/template_include/footer_google_analytics.inc" %>

<% } %>
</body>
</html>

<!-- end file footer.inc -->


