<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<HTML><HEAD>
<title>UrbanMinistry.org: Volunteering in Urban ministry, urban ministry sermons, MP3s, social networking, books, podcast, Christian workshops & presentations
</title>
   <meta name="Title" content="UrbanMinistry.org: Urban ministry sermons, MP3s, social networking, books, podcast, Christian workshops & presentations">
   <meta name="Description" content="UrbanMinistry.org: Urban ministry sermons, MP3s, social networking, books, podcast, Christian workshops & presentations">
   <meta name="Keywords" content="urban ministry, volunteer, christian volunteering, organizations">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<META NAME="ROBOTS" CONTENT="INDEX, NOFOLLOW">

<% String aszBodyClass=""; %>
   <link href="http://www.christianvolunteering.org/urbanministry/template/modular_um.css" type="text/css" rel="stylesheet">
<link href="http://www.urbanministry.org/themes/universal_assets/network_band/network-band.css" rel="stylesheet" type="text/css" />

<link href="http://www.christianvolunteering.org/urbanministry/template/navigation.css" rel="stylesheet" type="text/css" />
<link href="http://www.christianvolunteering.org/template_include/nice_menus.css" rel="stylesheet" type="text/css" />

<!--[if IE 6]>
	<link href="http://www.christianvolunteering.org/template_include/standard-wide-ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->


<!--DRUPAL NAVIGATION js (only needed for IE; CSS does it in other browsers)-->

<!--[if IE]>
<script type="text/javascript" src="/misc/jquery.js"></script>

<script type="text/javascript" src="/misc/drupal.js"></script>
<script type="text/javascript" src="/template_include/nice_menus.js"></script>
<![endif]-->
<link href="<%=request.getContextPath()%>/template_include/css/format_boxes_urbmin.css" rel="stylesheet" type="text/css" />
  <%@ include file="/template_include/menu_classes.inc" %>
</head>

<%@ include file="/template_include/network_band/network-band.inc" %>
<body id="urbmin" class="<%=aszBodyClass%>" >
<%@ include file="/template_include/facebookapi_keys.inc" %>
    <%@ include file="/template_include/facebook_graphapi_init.inc" %>
<div id="wrapper">
<div id="contentwrapper" class="home">

<div id="banner">
<div id="logo"><a href="http://www.urbanministry.org/"><img src="http://www.urbanministry.org/sites/all/themes/um/logo.png" alt="UrbanMinistry.org" border="0"></a></div>


<div id="search" class="home">

<div id="searchcontent">

<!--Include from /template/login_form.inc -->
<%@ include file="/template_include/login_form.inc" %>
<!--end: Include from /template/login_form.inc -->
</div>
</div>

<div id="ad-20989" class="image-advertisement"><a href="http://www.techmissioncorps.org/"><img height="65" width="270" title="Click to view Internship Opportunities" alt="Click to view Internship Opportunities" src="http://www.urbanministry.org/files/tmc_internship_ad-short.gif"></a></div> 

<div  class="cleardiv"></div>
</div>


<!-- END HEADER -->