<!-- BEGIN HEADER -->



<% if(aszHostID.equalsIgnoreCase( "voleng1" )) { %>
	<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
<% } else { %>
	<META NAME="ROBOTS" CONTENT="INDEX, NOFOLLOW">
<% } %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<title>Christians in Technology - Find Volunteer Opportunities at ChristianVolunteering.org</title>

<meta name="keywords" content="christian volunteer, Christian, church, Christian volunteering, Christian volunteer, church volunteer, nonprofit, community,service, urban ministry, youth, social justice, missions, short term missions, missionary, virtual volunteer, volunteer match, volunteer solutions, online volunteering, volunteer online, activism, youth work, digital divide, TechMission, CCDA, UYWI, Salvation Army, City Union Mission, Gospel Mission, World Vision">

<meta name="description" content="Christianvolunteering.org is the largest directory of Christian and church volunteer opportunities in the world providing opportunities in urban ministry, youth programs, short-term missions and virtual volunteering.">


<link href="/template_include/css/new_menu.css" rel="stylesheet" type="text/css" />
<link href="http://www.christianvolunteering.org/template_include/standard-wide.css" rel="stylesheet" type="text/css" />
<link href="http://www.christianvolunteering.org/template_include/technology.css" rel="stylesheet" type="text/css" />
<!--link href="/template_include/css/jazzy.css" rel="stylesheet" type="text/css" /-->
<!-- added by Anya - styling for nice_menu -->
<link href="http://www.christianvolunteering.org/template_include/navigation.css" rel="stylesheet" type="text/css" />
<link href="http://www.christianvolunteering.org/template_include/nice_menus.css" rel="stylesheet" type="text/css" />


<!--[if IE 6]>
	<link href="http://www.christianvolunteering.org/template_include/standard-wide-ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->

<!--DRUPAL NAVIGATION js - added by Akeem 2008-03-26-->

<script type="text/javascript" src="http://www.urbanministry.org/misc/jquery.js"></script>

<script type="text/javascript" src="http://www.urbanministry.org/misc/drupal.js"></script>
<script type="text/javascript" src="http://www.urbanministry.org/modules/nice_menus/nice_menus.js"></script>
<!-- end Drupal navigation js -->


<script type="text/JavaScript">
<!--
function MM_preloadImages() {
 //v3.0
  var d=document;
 if(d.images){
 if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments;
 for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){
 d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}}

function MM_swapImgRestore() { 
//v3.0
  var i,x,a=document.MM_sr;
 for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++)
 x.src=x.oSrc;}
function MM_findObj(n, d) {
 //v4.01  var p,i,x;  
if(!d) d=document; 
if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document;
 n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n];
 for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n);
 return x;}function MM_swapImage() { //v3.0  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}}
//-->
</script>
</head>
<body id="chrisvol"  onload="MM_preloadImages('imgs/nav_home_on.gif','imgs/nav_search_on.gif','imgs/nav_volunteer_on.gif','imgs/nav_nonprofits_on.gif','imgs/nav_myaccount_on.gif','imgs/nav_training_on.gif','imgs/nav_about_on.gif'); init();">

<div id="wrapper">

<div id="contentwrapper" class="home">

<div id="banner" class="home">

<div id="logo">
	<a href="http://www.gospel.com/" id="brand"><img width=260 height=95 src="http://www.christianvolunteering.org/images/ChrisInTech_CVorg.jpg" border="0" alt="A Community of Online Ministries" /></a>
	<a href="http://www.christianvolunteering.org/" id="cv_brand"><img src="http://www.christianvolunteering.org/imgs/logo_CV_color_72dpi.gif" width="350" border="0" title="Christian Volunteer Directory: Matching Volunteers with Urban Ministries" alt="ChristianVolunteerting.org" /></a>
</div>

<%@ include file="/template_include/login_form.inc" %>
<div  class="cleardiv"></div>
</div>
