<!-- BEGIN Footer -->

<div id="footer">
<!-- begin:  LINKS -->
<table class="footer_sections" cellspacing="0">
<tr>
	<td class="footer_sections_left">Partner Volunteer Sites: </td>
	<td class="footer_sections_right">
		<!--a href="http://ccda.christianvolunteering.org">CCDA</a><br/-->
		<a href="http://uywi.christianvolunteering.org" title="ChristianVolunteering.org: Christian Volunteer and Short Term Missions Opportunities">UYWI</a><br/>
		<a href="http://hlic.christianvolunteering.org" title="Here's Life Inner City">HLIC</a><br/>
		<a href="http://missionamerica.christianvolunteering.org" title="ChristianVolunteering.org: Christian Volunteer and Short Term Missions Opportunities">Mission America</a>
	</td>
	<td class="footer_sections_right">
		<a href="http://agrm.christianvolunteering.org" title="ChristianVolunteering.org: Christian Volunteer and Short Term Missions Opportunities">AGRM</a><br/>
		<a href="http://putyourfaithinaction.christianvolunteering.org" title="TechMission Faith In Action Volunteer Engine">FaithInAction</a><br/>
		<a href="<%=aszPortal%>/register.do?method=showSyndicationPartners">Syndication Partners</a>
	</td>
	<td class="footer_sections_right">
		<!--<a href="http://salvationarmy.christianvolunteering.org">Salvation Army</a><br/> -->
		<a href="http://gospel.christianvolunteering.org" title="ChristianVolunteering.org: Christian Volunteer and Short Term Missions Opportunities">Gospel.com</a><br/>
		<a href="http://www.catholicvolunteering.org" title="Search thousands of Catholic short term missions trips an volunteer opportunities: CatholicVolunteering.org">Catholic Volunteer Opportunities</a><br/>
	</td>
</tr>

<% if(  (aszHostID.equalsIgnoreCase("voleng1")) ||
		(aszHostID.equalsIgnoreCase("volengdefault")) 
){ %>  
<tr>
	<td class="footer_sections_left"> Regional Volunteer Sites:</td>
	<td class="footer_sections_right">
		<a href='http://www.christianvolunteering.org/s/ct/Los_Angeles,_CA/ctp/opp/results.jsp#fq=city_tax:"Los Angeles, CA"&fq=content_type:opportunity' title="Los Angeles, CA: Christian Volunteer and Short Term Missions Opportunities: ChristianVolunteering.org">Los Angeles, CA</a><br/>
		<a href='http://www.christianvolunteering.org/s/ct/New_York,_NY/ctp/opp/results.jsp#fq=city_tax:"New York, NY"&fq=content_type:opportunity' title="New York, NY: Christian Volunteer and Short Term Missions Opportunities: ChristianVolunteering.org">New York, NY</a><br/>
		<a href='http://www.christianvolunteering.org/s/ct/Chicago,_IL/ctp/opp/results.jsp#fq=city_tax:"Chicago, IL"&fq=content_type:opportunity' title="Chicago, IL: Christian Volunteer and Short Term Missions Opportunities: ChristianVolunteering.org">Chicago, IL</a><br/>
		<a href='http://www.christianvolunteering.org/s/ct/Boston,_MA/ctp/opp/results.jsp#fq=city_tax:"Boston, MA"&fq=content_type:opportunity' title="Boston, MA: Christian Volunteer and Short Term Missions Opportunities: ChristianVolunteering.org">Boston, MA</a>
	</td>
	<td class="footer_sections_right">
		<a href='http://www.christianvolunteering.org/s/ct/Atlanta,_GA/ctp/opp/results.jsp#fq=city_tax:"Atlanta, GA"&fq=content_type:opportunity' title="Atlanta, GA: Christian Volunteer and Short Term Missions Opportunities">Atlanta, GA</a><br/>
		<a href='http://www.christianvolunteering.org/s/ct/Washington,_DC/ctp/opp/results.jsp#fq=city_tax:"Washington, DC"&fq=content_type:opportunity' title="Washington, DC: Christian Volunteer and Short Term Missions Opportunities">Washington, DC</a><br/>
		<a href='http://www.christianvolunteering.org/s/ct/Philadelphia,_PA/ctp/opp/results.jsp#fq=city_tax:"Philadelphia, PA"&fq=content_type:opportunity' title="Philadelphia, PA: Christian Volunteer and Short Term Missions Opportunities">Philadelphia, PA</a><br/>
		<a href='http://www.christianvolunteering.org/s/ct/Dallas,_TX/ctp/opp/results.jsp#fq=city_tax:"Dallas, TX"&fq=content_type:opportunity' title="Dallas, TX: Christian Volunteer and Short Term Missions Opportunities">Dallas, TX</a>
	</td>

	<td class="footer_sections_right">
                <a href='http://www.christianvolunteering.org/oppsrch.do?method=processSearch&fq=city_tax:%22Minneapolis-St.%20Paul,%20MN%22&fq=content_type:opportunity#fq=city_tax:%22Minneapolis-St.%20Paul,%20MN%22&fq=content_type:opportunity' title="Minneapolis-St. Paul: Christian Volunteer and Short Term Missions Opportunities">Minneapolis-St. Paul, MN</a><br/>
		<!--a href='http://www.christianvolunteering.org/s/ct/Minneapolis-St;_Paul,_MN/ctp/opp/results.jsp#fq=city_tax:"Minneapolis-St. Paul, MN"&fq=content_type:opportunity' title="Minneapolis-St. Paul: Christian Volunteer and Short Term Missions Opportunities">Minneapolis-St. Paul, MN</a><br/-->
		<a href='http://www.christianvolunteering.org/s/ct/San_Diego,_CA/ctp/opp/results.jsp#fq=city_tax:"San Diego, CA"&fq=content_type:opportunity' title="San Diego, CA: Christian Volunteer and Short Term Missions Opportunities">San Diego, CA</a><br/>
		<a href="http://www.christianvolunteering.org/zipmap.jsp" title="Christian Volunteer Network Sitemap">Zip Code Sitemap</a><br/>
		<a href="/virtualvolunteer.jsp" title="Virtual Volunteer and Online Volunteering Opportunities: ChristianVolunteering.org">Virtual Volunteering</a>
	</td>
</tr>
<% } %>

<tr>
	<td class="footer_sections_left">Sections:</td>
	<td class="footer_sections_right">
                <a href="http://www.christianvolunteering.org/foundationgrants.jsp" title="Christin Foundation Grants">Christian Foundation Grants Directory</a><br/>
		<a href="http://www.christianvolunteering.org/churchvolunteer.jsp" title="Church Volunteers' Resources and Search">Church Volunteer Resources</a><br/> 
		<a href="http://www.christianvolunteering.org/shorttermmissions.jsp" title="Short Term Missions Trip Search">Short Term Missions</a><br/>
		<a href="/christianfamilyvolunteering.jsp" title="Christian family volunteer opportunities, family short-term missions trips, service learning">Christian Family Volunteering</a><br/>
		<a href="/medicalmissions.jsp" title="Medical Missions Volunteering">Medical Missions Volunteering</a>
	</td>
	<td class="footer_sections_right">
		<a href="/organizationlistings.jsp" title="Christian Volunteer and Short Term Missions Organizations">Organization Sitemap</a><br/>
		<a href="/directoryorgs.jsp" title="ChristianVolunteering.org: Christian Volunteer and Short Term Missions Organizations">Organization Directory</a><br/>
		<a href="http://www.christianvolunteering.org/christiangapyear.jsp" title="Christian gap year volunteer internships and short-term missions">Christian Gap Year</a><br/>
		<a href="http://www.christianvolunteering.org/disasterrelief.jsp" title="Christian Disaster Relief Volunteering">Christian Disaster Relief Volunteering</a><br/>
		<a href="http://www.urbanministry.org/wiki/encyclopedia-volunteer-management-volunteering-and-short-term-missions" title="UrbanMinistry.org | Encyclopedia of Volunteering: Encyclopedia of Urban Ministry">Volunteer Management Wiki</a><br/>
	</td>
	<td class="footer_sections_right">
		<a href="/volunteerlistings.jsp" title="Christian volunteer, church volunteer, urban ministry service, and short term missions volunteer listings">Volunteer Listings</a><br/>
		<a href="/directory.jsp" title="Christian volunteer, church volunteer, urban ministry service, and short term missions volunteer listings">Volunteer Sitemap</a><br/>
		<a href="/christianorphanage.jsp" title="Volunteer in a Christian Orphanage: Find Missions Trips: ChristianVolunteering.org">Volunteer in a Christian Orphanage </a><br/>
		<a href="/technologymissions.jsp" title="Volunteer in Technology in Missions">Volunteer in Technology in Missions</a><br/>
		<a href="/christianjobs.jsp" title="Christian Jobs in Ministry">Christian Jobs in Ministry</a>
	</td>
</tr>

<tr>
	<td class="footer_sections_left">TechMission Sites:</td>
	<td class="footer_sections_right">
<a href="http://www.techmission.org" title="Technology and Urban Ministry, Christian Community Computer Centers Addressing the Digital Divide">TechMission.org</a><br/>
<a href="http://www.urbanministry.org" title="UrbanMinistry.org: Urban ministry MP3s, talks, podcast, workshops, presentations, Webcasts, training, on racism, racial reconciliation, ethnic identity, classism, sexism, grants">UrbanMinistry.org</a><br/>
	</td>
	<td class="footer_sections_right">
	<a href="http://www.cityvision.edu" title="Online Urban Ministry Courses in Theology, Missions, Accounting, CFRE Fundraising, Management, Evangelism and Counseling">CityVision.edu</a><br/>
<a href="http://www.ilsnova.com">ILS NOVA: Adult Basic Education, Christian GED</a><br />
<a href="http://www.safefamilies.org" title="Free Parental Controls & Internet Filtering Software We-Blocker Download - Online Safety Workshops - Christian Accountability, Pornography and Sex Addiction Recovery">
SafeFamilies.org</a><br/>
	</td>
	<td class="footer_sections_right">
		<a href="http://www.cityvisioninternships.org" title="One Year and Summer Christian College Work Study Internships in Urban Ministry">Christian Ministry Internships</a>
                <a href="http://www.christianfreeware.org/" title="Free Christian Software CD for download including church management software, worship projection, accountability software, freeware, open source ministry and Bible software"> 
		ChristianFreeware.org</a><br/>
		<a href="http://www.christianvolunteering.org" title="Christian Volunteer Directory: Volunteering for Urban Ministries and Short Term Urban Missions Opportunities">Volunteer: ChristianVolunteering.org</a> <br/>
	</td>
</tr>

</table><!-- end:LINKS -->

<table class="footer_links"><!-- Table that contains share buttn and CV links-->
<tr>
 <td style="text-align: left; width:50px; padding-top: 30px;"></td> 

<!-- ADS INSERTED HERE -->
<td>
<div class="advertisement" id="group-tids-4496">
<script type="text/javascript" src="http://www.christianvolunteering.org/modules_um/ad/serve.php?q=1&amp;k=7a15268e1dcf7769adc47075b2f267d1&amp;t=4496"></script>
</div>
</td>

<!--/ADS INSERTED-->

<td class="copyright">

<p>
<a href="http://www.urbanministry.org/frontpageview/feed"><img src="http://www.urbanministry.org/imgs/Facebook_Buttons_Images/SocialMediaImages4CVFooter.jpg" alt="social media networks" border="0" align="texttop" usemap="#Map"/>
<map name="Map">
  <area shape="rect" coords="0,2,22,24" href="http://www.facebook.com/christianvolunteering">
  <area shape="rect" coords="25,2,47,21" href="http://www.youtube.com/techmissioninc">
  <area shape="rect" coords="48,2,73,20" href="http://twitter.com/remotefaith">
</map>
</a>
</p>

<p style="font-size: 1.2em;"><a style="text-decoration:underline" href="mailto:info@christianvolunteering.org">Email us</a> for support.</p>

<p>
<!-- main page feed -->
<a href="http://www.urbanministry.org/frontpageview/feed"><img src="http://www.urbanministry.org/files/images/rss-sm.png" align="texttop" alt="RSS" title="RSS feed" width="16" height="16" /> RSS</a> |
<!--/ main page feed -->
<!-- Buttn Facebook -->
<script>function fbs_click() {u=location.href;t=document.title;window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');return false;}</script>
<a href="http://www.facebook.com/share.php?u=<url>" class="fb_share_button" onclick="return fbs_click()" target="_blank" style="text-decoration:none;">Share</a> |
<!--/ Buttn Facebook -->
<a href="http://www.urbanministry.org/terms">privacy</a> | 
<a href="http://www.christianvolunteering.org/apiaccess.jsp">api</a> |
<a href="<%=aszPortal%>/contact.jsp" title="Contact Christian Volunteering">contact</a> | 
<a href="mailto:info@christianvolunteering.org">help</a> | 
<a href="https://www.urbanministry.org/civicrm/contribute/transact?reset=1&id=13"><img height="16" align="texttop" title="donate to TechMission" alt="donate" src="http://www.urbanministry.org/imgs/donate.gif"/></a> <br/> 
  
</p>
</td>

</tr>
</table><!-- end: Table that contains UM logo, share buttn and UM links-->

<script type="text/javascript" src="http://www.urbanministry.org/themes/universal_assets/network_band/network-band.js"></script>
