<!-- start file footer_google_analytics_goal_pages_secondary.inc -->

<script type="text/javascript">

var _gaq2 = _gaq2 || [];
  
_gaq2.push(   
	['_setAccount', 'UA-768097-3'],   
		['_trackPageview','<%=aszGoalPage%>'],   
	['b._setAccount', 'UA-768097-10'],   
		['b._trackPageview','<%=aszGoalPage%>'] 
<% if (aszHostID.equalsIgnoreCase("volengnewengland")) { %>
	,['c._setAccount', 'UA-768097-17'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengcatholic")) { %>
	,['c._setAccount', 'UA-768097-40'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengchurch")) { %>
	,['c._setAccount', 'UA-768097-56'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengabs")) { %>
	,['c._setAccount', 'UA-768097-44'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengagrm")) { %>
	,['c._setAccount', 'UA-768097-47'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<%} else if ( (aszHostID.equalsIgnoreCase("volengccda")) ||
(aszHostID.equalsIgnoreCase("volengchicago")) ){ %>
	,['c._setAccount', 'UA-768097-13'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
	,['d._setAccount', 'UA-768097-16'],   
		['d._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengesa")) { %>
	,['c._setAccount', 'UA-768097-45'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengfacebook")) { %>
	,['c._setAccount', 'UA-768097-52'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengfacebookivol")) { %>
	,['c._setAccount', 'UA-768097-53'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengfycsandbox")) { %>
	,['c._setAccount', 'UA-768097-55'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengfamily")) { %>
	,['c._setAccount', 'UA-768097-34'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengfia")) { %>
<%//var partnerTracker = _gat._getTracker("UA-1803221-1");%>
	,['c._setAccount', 'UA-768097-35'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if ( (aszHostID.equalsIgnoreCase("volenggospel")) ||
(aszHostID.equalsIgnoreCase("volenggospelcom")) ) {%>
	,['c._setAccount', 'UA-768097-23'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if ( (aszHostID.equalsIgnoreCase("volenghlic"))  ||
(aszHostID.equalsIgnoreCase("volengnewyork")) ){ %>
	,['c._setAccount', 'UA-768097-14'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengmissionamerica")) { %>
	,['c._setAccount', 'UA-768097-33'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengpartners")) { %>
	,['c._setAccount', 'UA-768097-38'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengroundtrip")) { %>
	,['c._setAccount', 'UA-768097-46'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengsaddleback")) { %>
	,['c._setAccount', 'UA-768097-31'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if (aszHostID.equalsIgnoreCase("volengsalvationarmy")) { %>
	,['c._setAccount', 'UA-768097-30'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if ( (aszHostID.equalsIgnoreCase("volenguywi")) ||
(aszHostID.equalsIgnoreCase("volenguywi")) ) {%>
	,['c._setAccount', 'UA-768097-41'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if ( (aszHostID.equalsIgnoreCase("volengworldvision")) ||
(aszHostID.equalsIgnoreCase("volenguywi")) ) {%>
	,['c._setAccount', 'UA-768097-43'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<% } else if ( (aszHostID.equalsIgnoreCase("volengyouthpartners")) ||
(aszHostID.equalsIgnoreCase("volengdenver")) ) {%>
	,['c._setAccount', 'UA-768097-15'],   
		['c._trackPageview','<%=aszGoalPage%>'] 
<%} %>
);

</script>
<!-- end file footer_google_analytics.inc -->

