 <h5><a href="<%=aszPortal%>/volunteergettingstarted.jsp" title="Register to Volunteer">VOLUNTEERS</a></h5>
        <ul class="navbullet">
		
		<li><a href="<%=aszPortal%>/volunteergettingstarted.jsp">Getting Started</a></li>
		<li><a href="<%=aszPortal%>/advancedsearch.jsp">Search Opportunities</a></li>
        <li><a href="http://www.urbanministry.org/redirect-home">Browse Opportunities</a></li>
<% if(!(aszSecondaryHost.equalsIgnoreCase( "volengivol" ))){ %>
        <li><a href="<%=aszPortal%>/shorttermmissions.jsp" >Short Term Missions</a></li>      
<% } %>
 </ul>
