<h1>Search Opportunities</h1>
<form name="searchForm2" method="get" action="<%=aszPortal%>/oppsrch.do">
<input type="hidden" name="method" value="processOppSearchTop">
  <table width="100%" border="0" cellpadding="0" cellspacing="5" style="font-size: 11px;">
   <tr>
    	
      <td width="65" align="right">Postal Code</td>
      <td><input style="width:80px;" type="text" name="postalcode" maxlength="5" />
              <A href="javascript:runSearch2();"><img src="http://www.christianvolunteering.org/imgs/search_arrow.gif" alt="go" width="19" height="19" border="0" align="absmiddle" /></A>
</td>
      </tr>
    <tr>
    	
      <td>&nbsp;</td>
      <td><a href="<%=aszPortal%>/advancedsearch.jsp" title="Advanced Search for Christian Volunteer Opportunities">advanced search</a></td>
      </tr>
  </table>
</form>

