<!-- BEGIN Footer -->
</div>



<div id="footer">
<a href="http://www.techmission.org/about/privacypolicy.php">privacy policy</a> | <a href="<%=request.getContextPath()%>/register.do?method=showContact">contact us</a> | <a href="mailto:feedback@christianvolunteering.org">feedback</a> | <a href="<%=request.getContextPath()%>/register.do?method=showSitemap">sitemap</a> | <a href="http://www.guidestar.org/partners/networkforgood/donate.jsp?ein=68-0492427">donate</a> | <a href="http://www.techmission.org">techmission.org</a> | <a href="http://www.safefamilies.org">safefamilies.org</a> | <a href="http://www.techmission.org/cd/tmnonprofit.php">Nonprofit Freeware</a> <br />

